name: xyz
description: "Comming soon"
version: 0.0.1
homepage: https://github.com/Tim-Solution/xyz

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0